<footer>
        <div class="footer">
            <div class="footer-section-1">
                <div class="footer-information">
                    <div class="About-us">
                        <input type="checkbox" id="about-toggle" class="toggle-checkbox">
                        <label for="about-toggle" class="section-header">
                            <h4>About us</h4>
                            <div class="chevron"></div>  
                        </label>
                        <div class="section-content">
                            <ol class="section-inner">
                                <li><a class="links">Emails</a></li>
                                <li><a class="links" href="index.php">Company</a></li>
                                <li><a class="links" href="jobs.php">Job opportunities</a></li>
                            </ol>
                        </div>
                    </div>
                    
                    <div class="customer-service">
                        <input type="checkbox" id="service-toggle" class="toggle-checkbox">
                        <label for="service-toggle" class="section-header">
                            <h4>customer service</h4>
                            <div class="chevron"></div>
                        </label>
                        <div class="section-content">
                            <ol class="section-inner">
                                <li><a class="links" href="about.php">Q&A</a></li>
                                <li><a class="links" href="about.php">Contact us</a></li>
                            </ol>
                        </div>
                    </div>
                    
                    <div class="hyperlinks">
                        <input type="checkbox" id="hyperlinks-toggle" class="toggle-checkbox">
                        <label for="hyperlinks-toggle" class="section-header">
                            <h4>hyperlinks</h4>
                            <div class="chevron"></div>
                        </label>
                        <div class="section-content">
                            <ol class="section-inner">
                                <li><a class="links" href="https://www.instagram.com/hienthong_/">Chung Hien Thong</a></li>
                                <li><a class="links" href="https://www.instagram.com/brian.huytr/">Tran Quang Huy</a></li>
                                <li><a class="links" href="https://www.instagram.com/khang_dangdeptrai/">Dang Gia Khang</a></li>
                                <li><a class="links" href="https://www.instagram.com/_ndawn._/">Nguyen Nhat Dan</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="logo-image">
                    <a href="index.php" class="home-link">
                        <img id="group-logo-footer" class="group-logo" src="../images/image.png" alt="DoangNhanLogo">
                    </a>
                </div>
            </div>

            <div class="footer-section-3">
                <p> <a class="hyperlinks-footer" href="https://www.swinburne.edu.au">© Swinburne University of
                        Technology</a> / <a class="hyperlinks-footer"
                        href="https://github.com/WebTechnologyProject-Sep2025/projectpart2-cos10026-2-group-3-1"
                        target="_blank" rel="noopener noreferrer">Github Repository</a> / <a class="hyperlinks-footer"
                        href="https://tqhuy250907.atlassian.net/jira/software/projects/DPG3/boards/68">Doanh Nhan
                        jira</a> </p>
            </div>
        </div>
    </footer>
