<input type="checkbox" id="burger-toggle" class="burger-toggle">
    
    <label for="burger-toggle" class="burger-menu">
        <img class="burger-image" src="../svg/burger-menu-svgrepo-com.svg">
    </label>
    <div class="nav-bar">
                    <a href="index.php">Home</a>
                    <a href="apply.php">Jobs</a>
                    <a href="jobs.php">Description</a>
                    <a href="about.php">About us</a>
                    <a href="enhancements.php">Enhancements</a>
                    <a href="login.php">Login</a>
    </div>
</div>
</header>